require:
  - rubocop-performance

AllCops:
  AutoCorrect: false
  Exclude:
    - 'click_house.gemspec'
    - 'bin/*'
    - 'spec/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.7

Bundler/OrderedGems:
  Enabled: false

# ============================== Documentation ======================
Style/Documentation:
  Enabled: false

# =============================== Performance =======================
Performance/AncestorsInclude:
  Enabled: true
Performance/BigDecimalWithNumericArgument:
  Enabled: true
Performance/RedundantSortBlock:
  Enabled: true
Performance/RedundantStringChars:
  Enabled: true
Performance/ReverseFirst:
  Enabled: true
Performance/SortReverse:
  Enabled: true
Performance/Squeeze:
  Enabled: true
Performance/StringInclude:
  Enabled: true

# ============================== Metrics ============================
Metrics/ClassLength:
  Max: 180
Metrics/BlockLength:
  Enabled: true
Metrics/MethodLength:
  Max: 25
Metrics/LineLength:
  Max: 140
Metrics/AbcSize:
  Max: 40

# ============================== Naming =============================
Naming/PredicateName:
  ForbiddenPrefixes:
    - is_
Naming/FileName:
  Enabled: true
  Exclude:
    - 'Gemfile'
Naming/MethodParameterName:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false

# ============================== Layout =============================
Layout/HashAlignment:
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/CaseIndentation:
  EnforcedStyle: case
  IndentOneStep: false
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented
Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: space
Layout/EmptyLines:
  Enabled: true
Layout/EmptyLineAfterMagicComment:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Enabled: true
Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/HeredocIndentation:
  Enabled: false
Layout/RescueEnsureAlignment:
  Enabled: false
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true

# ============================== Style ==============================
Style/RescueModifier:
  Enabled: true
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '[]'
    '%i':    '[]'
    '%w':    '[]'
  Exclude:
    - 'config/routes.rb'
Style/StringLiterals:
  Enabled: true
Style/AsciiComments:
  Enabled: false
Style/Copyright:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/Alias:
  Enabled: true
  EnforcedStyle: prefer_alias_method
Style/ClassAndModuleChildren:
  Enabled: true
  EnforcedStyle: nested
Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: no_comma
Style/RescueStandardError:
  Enabled: true
  EnforcedStyle: explicit
Style/InverseMethods:
  AutoCorrect: false
  Enabled: true
Style/IfUnlessModifier:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Style/BlockComments:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/ExponentialNotation:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/RedundantFetchBlock:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true
Style/AccessorGrouping:
  Enabled: false
Style/ArrayCoercion:
  Enabled: true
Style/BisectedAttrAccessor:
  Enabled: true
Style/CaseLikeIf:
  Enabled: true
Style/HashAsLastArrayItem:
  Enabled: true
Style/HashLikeCase:
  Enabled: true
Style/RedundantAssignment:
  Enabled: true
Style/RedundantFileExtensionInRequire:
  Enabled: true
Style/ExplicitBlockArgument:
  Enabled: true
Style/GlobalStdStream:
  Enabled: true
Style/OptionalBooleanParameter:
  Enabled: true
Style/SingleArgumentDig:
  Enabled: true
Style/StringConcatenation:
  Enabled: true

# ============================== Lint ==============================
Lint/DuplicateMethods:
  Enabled: false
Lint/AmbiguousOperator:
  Enabled: false
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Lint/DuplicateElsifCondition:
  Enabled: true
Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true
Lint/DuplicateRescueException:
  Enabled: true
Lint/EmptyConditionalBody:
  Enabled: true
Lint/FloatComparison:
  Enabled: true
Lint/MissingSuper:
  Enabled: false
Lint/OutOfRangeRegexpRef:
  Enabled: true
Lint/SelfAssignment:
  Enabled: true
Lint/TopLevelReturnWithArgument:
  Enabled: true
Lint/UnreachableLoop:
  Enabled: true
