name: CI

on: [push, pull_request]

jobs:
  rspec:
    runs-on: ubuntu-latest

    services:
      clickhouse:
        image: yandex/clickhouse-server:22.1
        ports: 
          - 8123:8123

    strategy:
      matrix:
        ruby-version: [3.1, '3.0', 2.7, 2.6]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # 'bundle install' and cache

      - name: Run tests
        run: bundle exec rspec

  rubocop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true # 'bundle install' and cache

      - name: Run Rubocop
        run: bundle exec rubocop
